version: "3"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django-challenge
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  web:
    build: ./djangochallenge
    command: python manage.py runserver 0.0.0.0:8000
  
    ports:
      - "8000:8000"
    depends_on:
      - db

