# Generated by Django 4.2.6 on 2023-10-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Name')),
                ('province', models.CharField(db_index=True, max_length=200, verbose_name='Province')),
                ('city', models.CharField(db_index=True, max_length=200, verbose_name='City')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('map_url', models.URLField(blank=True, verbose_name='Map URL')),
            ],
            options={
                'verbose_name': 'Stadium',
                'verbose_name_plural': 'Stadiums',
                'db_table': 'booking_stadiums',
                'ordering': ['id'],
                'unique_together': {('name', 'province', 'city')},
            },
        ),
    ]
