# Generated by Django 4.2.6 on 2023-10-26 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_stadium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('location', models.PositiveSmallIntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'VIP')], verbose_name='Location')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='Capacity')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_stadiums', to='booking.stadium', verbose_name='Stadium')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'db_table': 'booking_sections',
                'ordering': ['id'],
                'unique_together': {('stadium', 'location')},
            },
        ),
    ]
