# Generated by Django 4.2.6 on 2023-10-26 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('guest_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_guest_teams', to='booking.team', verbose_name='Guest Team')),
                ('host_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_host_teams', to='booking.team', verbose_name='Host Team')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_stadiums', to='booking.stadium', verbose_name='Stadium')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'db_table': 'booking_matches',
                'ordering': ['id'],
                'unique_together': {('stadium', 'host_team', 'guest_team', 'start_time')},
            },
        ),
    ]
