# Generated by Django 4.2.6 on 2023-10-26 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('seat_number', models.PositiveSmallIntegerField(verbose_name='Seat Number')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Sold'), (1, 'Reserved')], default=1, verbose_name='Status')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_invoices', to='booking.invoice', verbose_name='Invoice')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_matches', to='booking.match', verbose_name='Match')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_sections', to='booking.section', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'booking_tickets',
                'ordering': ['id'],
            },
        ),
    ]
