# Generated by Django 3.2.7 on 2021-10-04 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.CharField(max_length=255)),
                ('match_date', models.DateTimeField()),
                ('match_length', models.CharField(max_length=4, verbose_name='Match Length in minutes')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrationapp.stadium')),
            ],
        ),
    ]
