# Generated by Django 3.2.7 on 2021-10-04 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrationapp', '0002_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('seat_range', models.CharField(max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrationapp.match')),
            ],
        ),
    ]
