# Generated by Django 3.2.7 on 2021-10-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrationapp', '0003_seatmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatmanager',
            name='last_seat_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
