# Generated by Django 3.2.7 on 2021-10-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrationapp', '0004_seatmanager_last_seat_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seatmanager',
            unique_together={('match', 'team_name')},
        ),
    ]
