# Generated by Django 4.0 on 2021-12-26 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='match.match')),
                ('user', models.ManyToManyField(through='seat.BookSeat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'match')},
            },
        ),
        migrations.AddField(
            model_name='bookseat',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seat.seat'),
        ),
        migrations.AddField(
            model_name='bookseat',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AddConstraint(
            model_name='bookseat',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('seat', 'date', 'time'), name='unique seat per datetime'),
        ),
    ]
