# Generated by Django 4.0 on 2021-12-26 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_alter_match_unique_together'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('seat', '0002_alter_seat_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seat.seat'),
        ),
        migrations.AlterField(
            model_name='bookseat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.match'),
        ),
    ]
