# Generated by Django 4.0 on 2021-12-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_alter_match_unique_together'),
        ('seat', '0003_alter_bookseat_seat_alter_bookseat_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seat',
            name='unique seat per match',
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('name', 'match')},
        ),
    ]
