# Generated by Django 3.2.10 on 2021-12-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0004_remove_seat_unique seat per match_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookseat',
            name='unique seat per datetime',
        ),
        migrations.RenameField(
            model_name='bookseat',
            old_name='deleted',
            new_name='reserved',
        ),
        migrations.RemoveField(
            model_name='bookseat',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bookseat',
            name='time',
        ),
        migrations.AddConstraint(
            model_name='bookseat',
            constraint=models.UniqueConstraint(condition=models.Q(('reserved', True)), fields=('seat',), name='unique seat'),
        ),
    ]
