# Generated by Django 4.0 on 2021-12-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_alter_match_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='match',
            name='unique match per datetime and stadium',
        ),
    ]
