# Generated by Django 4.0 on 2021-12-26 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0001_initial'),
        ('match', '0003_remove_match_unique match per datetime and stadium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium.stadium'),
        ),
    ]
