# Generated by Django 4.0 on 2021-12-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0001_initial'),
        ('match', '0004_alter_match_stadium'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('name', 'stadium', 'date', 'time')},
        ),
    ]
