# Generated by Django 3.2.10 on 2021-12-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_alter_match_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
